/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprueba que la API responde.
         * @description Sonda de vida sin efectos secundarios. Devuelve `200` mientras el servicio este en pie; si no responde, el cliente debe asumir que la API no esta disponible.
         */
        get: operations["obtenerSalud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista el catalogo de tipos de solicitud.
         * @description Devuelve todas las entradas del catalogo externo de tipos. La lista puede venir vacia; eso no es un error.
         */
        get: operations["listarTipos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista los operadores de back-office.
         * @description Devuelve todos los operadores que pueden gestionar solicitudes. La lista puede venir vacia; eso no es un error.
         */
        get: operations["listarOperadores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitudes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista las solicitudes, opcionalmente filtradas por estado.
         * @description Devuelve todas las solicitudes. Si se indica `estado`, devuelve unicamente las que se encuentran en ese estado. Un filtro valido que no casa con ninguna solicitud produce `200` con un array vacio, no `404`.
         */
        get: operations["listarSolicitudes"];
        put?: never;
        /**
         * Crea una solicitud nueva.
         * @description Crea una solicitud a partir de un tipo del catalogo y un solicitante. La solicitud nace en estado `borrador` y sin operador asignado; el servidor le adjudica `id`, `referencia`, `creadaEn` y `actualizadaEn`.
         */
        post: operations["crearSolicitud"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitudes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador unico e interno de la solicitud.
                 * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
                 */
                id: components["parameters"]["IdSolicitud"];
            };
            cookie?: never;
        };
        /**
         * Obtiene una solicitud por su identificador.
         * @description Devuelve la solicitud cuyo `id` coincide con el de la ruta.
         */
        get: operations["obtenerSolicitud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitudes/{id}/transiciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador unico e interno de la solicitud.
                 * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
                 */
                id: components["parameters"]["IdSolicitud"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aplica una transicion de estado sobre una solicitud.
         * @description Ejecuta la accion indicada sobre la solicitud y devuelve la solicitud ya actualizada. Transiciones permitidas: `enviar` (borrador -> enviada), `aprobar` (enviada -> aprobada) y `rechazar` (enviada -> rechazada). Cualquier otra combinacion de estado y accion, incluidas las que parten de un estado final, se rechaza con `409`.
         */
        post: operations["aplicarTransicion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Estado de una solicitud dentro de la maquina de estados. `aprobada` y `rechazada` son estados finales.
         * @example enviada
         * @enum {string}
         */
        Estado: "borrador" | "enviada" | "aprobada" | "rechazada";
        /**
         * @description Accion que provoca una transicion de estado: `enviar` (borrador -> enviada), `aprobar` (enviada -> aprobada), `rechazar` (enviada -> rechazada).
         * @example aprobar
         * @enum {string}
         */
        Accion: "enviar" | "aprobar" | "rechazar";
        /** @description Solicitud de cliente gestionada por un operador de back-office. */
        Solicitud: {
            /**
             * Format: uuid
             * @description Identificador unico e interno de la solicitud.
             * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
             */
            id: string;
            /**
             * @description Codigo legible por humanos de la solicitud, unico y estable. Formato `SOL-<anyo>-<secuencial de 4 digitos>`.
             * @example SOL-2026-0007
             */
            referencia: string;
            /**
             * @description Identificador del tipo de solicitud en el catalogo externo de tipos. Se corresponde con `Tipo.id`.
             * @example alta-cuenta
             */
            tipo: string;
            /**
             * @description Cliente que presenta la solicitud.
             * @example Marta Ruiz Delgado
             */
            solicitante: string;
            /** @description Estado actual de la solicitud. */
            estado: components["schemas"]["Estado"];
            /**
             * @description Identificador del operador de back-office asignado a la solicitud, correspondiente a `Operador.id`. Es `null` cuando no hay ninguno asignado.
             * @example op-0042
             */
            operador: string | null;
            /**
             * Format: date-time
             * @description Instante de creacion de la solicitud (UTC, ISO 8601).
             * @example 2026-02-11T09:14:32Z
             */
            creadaEn: string;
            /**
             * Format: date-time
             * @description Instante de la ultima modificacion de la solicitud (UTC, ISO 8601). Coincide con `creadaEn` mientras no se haya modificado.
             * @example 2026-02-12T16:48:05Z
             */
            actualizadaEn: string;
        };
        /** @description Datos necesarios para crear una solicitud nueva. */
        NuevaSolicitud: {
            /**
             * @description Identificador del tipo de solicitud en el catalogo externo de tipos. Se corresponde con `Tipo.id`.
             * @example alta-cuenta
             */
            tipo: string;
            /**
             * @description Cliente que presenta la solicitud.
             * @example Marta Ruiz Delgado
             */
            solicitante: string;
        };
        /** @description Peticion para aplicar una transicion de estado sobre una solicitud. */
        PeticionTransicion: {
            /** @description Accion a aplicar sobre la solicitud. */
            accion: components["schemas"]["Accion"];
        };
        /** @description Entrada del catalogo externo de tipos de solicitud. */
        Tipo: {
            /**
             * @description Identificador unico del tipo en el catalogo.
             * @example alta-cuenta
             */
            id: string;
            /**
             * @description Nombre corto del tipo, para mostrar en la interfaz.
             * @example Alta de cuenta
             */
            nombre: string;
            /**
             * @description Explicacion del tipo de solicitud.
             * @example Apertura de una cuenta nueva para un cliente.
             */
            descripcion: string;
        };
        /** @description Operador de back-office que puede gestionar solicitudes. */
        Operador: {
            /**
             * @description Identificador unico del operador.
             * @example op-0042
             */
            id: string;
            /**
             * @description Nombre del operador, para mostrar en la interfaz.
             * @example Javier Nunez Prieto
             */
            nombre: string;
        };
        /** @description Respuesta devuelta cuando una operacion no se puede completar. */
        Error: {
            /**
             * @description Descripcion del error, legible por humanos.
             * @example La solicitud ya esta en un estado final.
             */
            mensaje: string;
            /**
             * @description Informacion adicional sobre el error, cuando existe.
             * @example Estado actual: aprobada; accion solicitada: rechazar.
             */
            detalle?: string;
        };
    };
    responses: {
        /** @description No existe ninguna solicitud con ese identificador. */
        SolicitudNoEncontrada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "mensaje": "La solicitud no existe.",
                 *       "detalle": "No hay ninguna solicitud con id '3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f'."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El identificador de la ruta no tiene formato UUID. */
        IdMalFormado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "mensaje": "El identificador de la solicitud no es valido.",
                 *       "detalle": "Valor recibido: 'SOL-2026-0007'. Se esperaba un UUID."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error inesperado del servidor. */
        ErrorInterno: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "mensaje": "Se ha producido un error inesperado."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Identificador unico e interno de la solicitud.
         * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
         */
        IdSolicitud: string;
        /**
         * @description Si se indica, devuelve unicamente las solicitudes que estan en ese estado. Si se omite, no se filtra.
         * @example enviada
         */
        FiltroEstado: components["schemas"]["Estado"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    obtenerSalud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La API esta operativa. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true
                     *     }
                     */
                    "application/json": {
                        /**
                         * @description Siempre `true` cuando la API responde.
                         * @example true
                         */
                        ok: boolean;
                    };
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarTipos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalogo de tipos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "alta-cuenta",
                     *         "nombre": "Alta de cuenta",
                     *         "descripcion": "Apertura de una cuenta nueva para un cliente."
                     *       },
                     *       {
                     *         "id": "cambio-titular",
                     *         "nombre": "Cambio de titular",
                     *         "descripcion": "Traspaso de la titularidad de una cuenta existente."
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Tipo"][];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarOperadores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de operadores. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "op-0042",
                     *         "nombre": "Javier Nunez Prieto"
                     *       },
                     *       {
                     *         "id": "op-0043",
                     *         "nombre": "Marta Ruiz Delgado"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Operador"][];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarSolicitudes: {
        parameters: {
            query?: {
                /**
                 * @description Si se indica, devuelve unicamente las solicitudes que estan en ese estado. Si se omite, no se filtra.
                 * @example enviada
                 */
                estado?: components["parameters"]["FiltroEstado"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitudes encontradas, ya filtradas si se indico `estado`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f",
                     *         "referencia": "SOL-2026-0007",
                     *         "tipo": "alta-cuenta",
                     *         "solicitante": "Marta Ruiz Delgado",
                     *         "estado": "enviada",
                     *         "operador": "op-0042",
                     *         "creadaEn": "2026-02-11T09:14:32Z",
                     *         "actualizadaEn": "2026-02-12T16:48:05Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Solicitud"][];
                };
            };
            /** @description El valor de `estado` no pertenece al enum `Estado`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "mensaje": "El filtro de estado no es valido.",
                     *       "detalle": "Valor recibido: 'pendiente'. Valores admitidos: borrador, enviada, aprobada, rechazada."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    crearSolicitud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Datos de la solicitud a crear. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "tipo": "alta-cuenta",
                 *       "solicitante": "Marta Ruiz Delgado"
                 *     }
                 */
                "application/json": components["schemas"]["NuevaSolicitud"];
            };
        };
        responses: {
            /** @description Solicitud creada. */
            201: {
                headers: {
                    /** @description Ruta de la solicitud recien creada. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f",
                     *       "referencia": "SOL-2026-0007",
                     *       "tipo": "alta-cuenta",
                     *       "solicitante": "Marta Ruiz Delgado",
                     *       "estado": "borrador",
                     *       "operador": null,
                     *       "creadaEn": "2026-02-11T09:14:32Z",
                     *       "actualizadaEn": "2026-02-11T09:14:32Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Solicitud"];
                };
            };
            /** @description El cuerpo no es valido: falta un campo obligatorio, el `tipo` no existe en el catalogo o el `solicitante` no es utilizable. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    obtenerSolicitud: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador unico e interno de la solicitud.
                 * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
                 */
                id: components["parameters"]["IdSolicitud"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitud encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f",
                     *       "referencia": "SOL-2026-0007",
                     *       "tipo": "alta-cuenta",
                     *       "solicitante": "Marta Ruiz Delgado",
                     *       "estado": "enviada",
                     *       "operador": "op-0042",
                     *       "creadaEn": "2026-02-11T09:14:32Z",
                     *       "actualizadaEn": "2026-02-12T16:48:05Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Solicitud"];
                };
            };
            400: components["responses"]["IdMalFormado"];
            404: components["responses"]["SolicitudNoEncontrada"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    aplicarTransicion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identificador unico e interno de la solicitud.
                 * @example 3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f
                 */
                id: components["parameters"]["IdSolicitud"];
            };
            cookie?: never;
        };
        /** @description Accion a aplicar sobre la solicitud. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "accion": "aprobar"
                 *     }
                 */
                "application/json": components["schemas"]["PeticionTransicion"];
            };
        };
        responses: {
            /** @description Transicion aplicada; se devuelve la solicitud actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f2a9c14-8b7d-4e5a-9f01-6c2d5e8a4b3f",
                     *       "referencia": "SOL-2026-0007",
                     *       "tipo": "alta-cuenta",
                     *       "solicitante": "Marta Ruiz Delgado",
                     *       "estado": "aprobada",
                     *       "operador": "op-0042",
                     *       "creadaEn": "2026-02-11T09:14:32Z",
                     *       "actualizadaEn": "2026-02-13T10:02:11Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Solicitud"];
                };
            };
            /** @description El identificador de la ruta no tiene formato UUID, o el cuerpo no es valido: falta `accion` o su valor no pertenece al enum `Accion`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["SolicitudNoEncontrada"];
            /** @description La transicion no esta permitida desde el estado actual de la solicitud. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
}
